name: TestBerlin
favicon: null
layout_spectrum: 0.20660728914663196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: 8a6d05b7-f48e-44cd-8822-3ad4a1ec964a
    url: null
typography_spectrum: 0.25872315978631377
